#!/bin/bash	  
#$ -V	 #Inherit the submission environment
#$ -cwd	 # Start job in submission directory
#$ -N myMPI	 # Job Name
#$ -j y	 # Combine stderr and stdout
#$ -o $JOB_NAME.o$JOB_ID	 # Name of the output file (eg. myMPI.oJobID)
#$ -pe 4way 300	 # Requests 12 tasks/node, 24 cores total
#$ -q normal	 # Queue name normal
#$ -A TG-AST090005
#$ -l h_rt=24:00:00	 # Run time (hh:mm:ss) - 1.5 hours
####$ -M boywert@mail.com	 # Address for email notification
####$ -m be	 # Email at Begin and End of job
set -x	 # Echo commands, use set echo with csh
export OMP_NUM_THREADS=3
/usr/bin/time ibrun tacc_affinity $1	 # Run the MPI executable named a.out

