#!/bin/bash	
#SBATCH -J normal_boyd        # Job Name
#SBATCH -o dev.o%j    # Output and error file name (%j expands to jobID)
#SBATCH -N 20 -n 80           # Total number of mpi tasks requested
#SBATCH -p normal  # Queue (partition) name -- normal, development, etc.
#SBATCH -t 01:00:00     # Run time (hh:mm:ss) - 1.5 hours
export OMP_NUM_THREADS=4
#export MKL_MIC_ENABLE=1
#export MIC_PREFIX=MIC  
#export MIC_OMP_NUM_THREADS=240  
#export KMP_AFFINITY=scatter
/usr/bin/time -p ibrun tacc_affinity $1           # Run the MPI executable named a.out
