#!/bin/bash	
#SBATCH -J dev_boyd        # Job Name
#SBATCH -o dev.o%j    # Output and error file name (%j expands to jobID)
#SBATCH -N 1 -n 1           # Total number of mpi tasks requested
#SBATCH -p development  # Queue (partition) name -- normal, development, etc.
#SBATCH -t 01:00:00     # Run time (hh:mm:ss) - 1.5 hours
export OMP_NUM_THREADS=1
#export MKL_MIC_ENABLE=1
#export MIC_PREFIX=MIC  
#export MIC_OMP_NUM_THREADS=240  
#export KMP_AFFINITY=scatter
/usr/bin/time -p ibrun tacc_affinity $1           # Run the MPI executable named a.out
